export type Role = 'ADMIN' | 'OPS' | 'ANALYST' | 'VIEWER';
export type DecimalLike = string | number;

export interface User { id:string; email:string; merchant_id:string; role:Role; is_active:boolean; created_at?:string; updated_at?:string }
export interface Payment { id:string; merchant_id?:string; provider:string; provider_payment_id:string; provider_order_id?:string|null; amount:DecimalLike; currency:string; status:string; method?:string|null; captured?:boolean; created_at:string; captured_at?:string|null }
export interface Refund { id:string; merchant_id?:string; provider:string; provider_refund_id:string; provider_payment_id?:string|null; payment_id?:string|null; amount:DecimalLike; currency:string; status:string; created_at:string; processed_at?:string|null }
export interface Settlement { id:string; merchant_id?:string; provider:string; provider_settlement_id:string; provider_payment_id?:string|null; payment_id?:string|null; gross_amount:DecimalLike; fee:DecimalLike; tax:DecimalLike; net_amount:DecimalLike; currency:string; status:string; utr?:string|null; settled_at:string }
export interface ReconciliationException { id:string; reconciliation_case_id?:string|null; exception_code:string; severity:string; status:string; source?:string|null; merchant_id?:string; primary_record_id?:string|null; related_record_id?:string|null; expected_amount:DecimalLike; actual_amount:DecimalLike; difference:DecimalLike; created_at:string }
export interface RCA { id?:string; root_cause:string; root_cause_code?:string; root_cause_category?:string; category?:string; explanation:string; confidence?:DecimalLike; confidence_label?:string; recommended_action:string; evidence_ids_json?:string[]; evidence_ids?:string[]; engine_version:string; generated_at?:string }
export interface Evidence { id:string; reconciliation_case_id?:string; evidence_type:string; source_entity_type?:string|null; source_record_id?:string|null; captured_at:string; relevance:string; snapshot_json?:unknown; description?:string; metadata_json?:unknown }
export interface Case { id:string; payment_id?:string|null; record_id?:string|null; record_type:string; case_type:string; severity:string; status:string; case_number:string; merchant_id?:string|null; title:string; description:string; priority:string; assigned_to?:string|null; updated_at:string; resolution_code?:string|null; resolution_note?:string|null; expected_amount:DecimalLike; actual_amount:DecimalLike; difference:DecimalLike; currency?:string; confidence?:DecimalLike; summary:string; created_at:string; resolved_at?:string|null; exceptions?:ReconciliationException[]; evidence?:Evidence[]; notes?:CaseNote[]; timeline?:CaseEvent[]; rca?:RCA|null }
export interface CaseNote { id:string; case_id:string; author_reference?:string|null; note:string; created_at:string }
export interface CaseEvent { id:string; case_id:string; event_type:string; actor_reference?:string|null; metadata_json?:unknown; created_at:string }
export interface AIHypothesis { hypothesis?:string; confidence?:string; [key:string]: unknown }
export interface AIInvestigation { summary:string; facts?:string[]; deterministic_findings:string[]; hypotheses:(string|AIHypothesis)[]; recommended_actions:string[]; evidence_references:(string|Record<string,unknown>)[]; uncertainty:unknown; safety_disclaimer?:string }
export interface AIInvestigationResponse { ai_investigation?:AIInvestigation; answer?:string; disclaimer?:string }
export interface Job { job_id:string; merchant_id?:string; job_type:string; status:'QUEUED'|'RUNNING'|'RETRYING'|'SUCCEEDED'|'FAILED'|'DEAD_LETTERED'|string; attempt_count:number; max_attempts:number; created_at:string; started_at?:string|null; completed_at?:string|null; next_retry_at?:string|null; last_error_code?:string|null; last_error_message_safe?:string|null; request_id?:string|null; created_by?:string|null; result?:unknown }
export interface AuditEvent { event_id:string; merchant_id?:string; actor_user_id?:string|null; actor_role?:Role|string|null; actor_type?:string; action:string; resource_type:string; resource_id?:string|null; request_id?:string|null; timestamp:string; outcome:string; ip_address?:string|null; metadata?:unknown; before_snapshot?:unknown; after_snapshot?:unknown; previous_event_hash?:string|null; event_hash?:string|null }
export interface IngestionBatch { id:string; merchant_id?:string; source:string; provider?:string|null; status:string; received_count?:number; created_count?:number; duplicate_count?:number; rejected_count?:number; started_at?:string|null; completed_at?:string|null; errors?:unknown }
export interface ReconciliationResult { id?:string; case_number?:string; status?:string; priority?:string; difference?:DecimalLike; currency?:string; rca?:RCA|null }
export interface ApiPage<T> { items:T[]; page:number; limit:number; total?:number; pages?:number }
export interface ApiError { status:number; message:string; requestId?:string }
