from enum import Enum

class EvidenceType(str, Enum):
    PAYMENT_RECORD = "PAYMENT_RECORD"
    REFUND_RECORD = "REFUND_RECORD"
    SETTLEMENT_RECORD = "SETTLEMENT_RECORD"
    BANK_TRANSACTION = "BANK_TRANSACTION"
    RECONCILIATION_RESULT = "RECONCILIATION_RESULT"
    EXCEPTION_RECORD = "EXCEPTION_RECORD"
    INGESTION_RECORD = "INGESTION_RECORD"
    WEBHOOK_EVENT = "WEBHOOK_EVENT"
    CASE_EVENT = "CASE_EVENT"
