from enum import Enum

class CaseStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    REOPENED = "REOPENED"

class CasePriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ResolutionCode(str, Enum):
    SETTLEMENT_POSTED = "SETTLEMENT_POSTED"
    REFUND_PROCESSED = "REFUND_PROCESSED"
    DUPLICATE_CONFIRMED = "DUPLICATE_CONFIRMED"
    BANK_CORRECTION_REQUIRED = "BANK_CORRECTION_REQUIRED"
    PROVIDER_INVESTIGATION_REQUIRED = "PROVIDER_INVESTIGATION_REQUIRED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    OTHER = "OTHER"

VALID_TRANSITIONS = {
    CaseStatus.OPEN: {CaseStatus.IN_PROGRESS, CaseStatus.RESOLVED},
    CaseStatus.IN_PROGRESS: {CaseStatus.RESOLVED},
    CaseStatus.RESOLVED: {CaseStatus.REOPENED},
    CaseStatus.REOPENED: {CaseStatus.IN_PROGRESS, CaseStatus.RESOLVED},
}
