'use client';
import {useEffect,useState} from 'react';
import {api} from '../../lib/api';
import {useAuth} from '../../lib/auth';
import {Badge,Button,ErrorState,Loading,PageTitle,Stat,Table} from '../../components/ui';
import {money,dateTime} from '../../lib/format';

function loadRazorpay(): Promise<void> {
 return new Promise((resolve,reject)=>{
  if((window as any).Razorpay){resolve();return;}
  const existing=document.querySelector('script[data-rcaa-razorpay]');
  if(existing){existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',()=>reject(new Error('Unable to load Razorpay Checkout')),{once:true});return;}
  const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.dataset.rcaaRazorpay='true';
  script.onload=()=>resolve();script.onerror=()=>reject(new Error('Unable to load Razorpay Checkout'));document.head.appendChild(script);
 });
}
export default function Billing(){
 const {user}=useAuth(); const [d,setD]=useState<any>(); const [plans,setPlans]=useState<any[]>([]); const [e,setE]=useState(''); const [busy,setBusy]=useState('');
 const load=()=>Promise.all([api<any>('/billing'),api<any>('/billing/plans')]).then(([b,p])=>{setD(b);setPlans(p.plans)}).catch(x=>setE(x.message)); useEffect(()=>{void load()},[]);
 async function choose(code:string){setBusy(code);setE('');try{const result:any=await api('/billing/checkout',{method:'POST',body:JSON.stringify({plan_code:code})});if(result.checkout?.provider==='RAZORPAY'&&result.checkout?.subscription_id){await loadRazorpay();await new Promise<void>((resolve,reject)=>{const options={key:result.checkout.key_id,subscription_id:result.checkout.subscription_id,name:result.checkout.name,description:result.checkout.description,prefill:result.checkout.prefill,handler:async(response:any)=>{try{await api('/billing/razorpay/verify',{method:'POST',body:JSON.stringify({razorpay_payment_id:response.razorpay_payment_id,razorpay_subscription_id:response.razorpay_subscription_id,razorpay_signature:response.razorpay_signature})});resolve()}catch(err){reject(err)}}};const checkout=new (window as any).Razorpay(options);checkout.on('payment.failed',(response:any)=>reject(new Error(response?.error?.description||'Razorpay payment failed')));checkout.open()});}await load()}catch(x:any){setE(x.message)}finally{setBusy('')}}
 async function activate(code:string){setBusy('activate-'+code);try{await api('/billing/subscription/activate',{method:'POST',body:JSON.stringify({plan_code:code})});await load()}catch(x:any){setE(x.message)}finally{setBusy('')}}
 async function paid(id:string){setBusy('paid-'+id);try{await api(`/billing/invoices/${id}/mark-paid`,{method:'POST'});await load()}catch(x:any){setE(x.message)}finally{setBusy('')}}
 if(e&&!d)return <ErrorState message={e} onRetry={load}/>; if(!d)return <Loading/>; const s=d.subscription,u=s.usage||{};
 return <><PageTitle title="Billing" description="Subscription, usage and invoices for this RCAA workspace."/>{e&&<p className="error">{e}</p>}
 <section className="grid stats"><Stat label="Current plan" value={s.plan_name}/><Stat label="Status" value={<Badge value={s.status}/>}/><Stat label="Monthly price" value={money(s.monthly_price,'INR')}/><Stat label="Transactions used" value={`${u.billable_transactions||0} / ${s.monthly_transaction_limit||'—'}`}/></section>
 <section className="cards"><div className="panel"><h3>Current subscription</h3><Table><tbody><tr><th>Plan</th><td>{s.plan_name}</td></tr><tr><th>Status</th><td><Badge value={s.status}/></td></tr><tr><th>Period</th><td>{dateTime(s.current_period_start)} → {dateTime(s.current_period_end)}</td></tr><tr><th>Provider</th><td>{s.provider}</td></tr><tr><th>Provider subscription</th><td>{s.provider_subscription_id||'—'}</td></tr><tr><th>Cancellation</th><td>{s.cancel_at_period_end?'Scheduled':'Not scheduled'}</td></tr></tbody></Table></div>
 <div className="panel"><h3>Current usage</h3><Table><tbody><tr><th>Payments</th><td>{u.payments_processed||0}</td></tr><tr><th>Settlements</th><td>{u.settlements_processed||0}</td></tr><tr><th>Reconciliation runs</th><td>{u.reconciliation_runs||0}</td></tr><tr><th>Exceptions</th><td>{u.exceptions_created||0}</td></tr><tr><th>Usage</th><td>{u.billable_transactions||0} / {s.monthly_transaction_limit||'—'} ({s.monthly_transaction_limit?Math.min(100,Math.round((u.billable_transactions||0)/s.monthly_transaction_limit*100)):0}%)</td></tr></tbody></Table></div></section>
 <div className="panel" style={{marginTop:14}}><h3>Plans</h3><div className="cards">{plans.filter(p=>p.code!=='TRIAL').map(p=><div className="metric" key={p.code}><span>{p.name}</span><b>{money(p.monthly_price,'INR')} / month</b><p className="muted">Up to {Number(p.transaction_limit).toLocaleString()} billable transactions</p><Button disabled={busy!==''} onClick={()=>choose(p.code)}>{busy===p.code?'Requesting…':'Request plan'}</Button>{s.provider!=='RAZORPAY'&&user?.role==='ADMIN'&&s.plan_code===p.code&&s.status!=='ACTIVE'&&<button className="btn secondary" style={{marginLeft:8}} disabled={busy!==''} onClick={()=>activate(p.code)}>{busy==='activate-'+p.code?'Activating…':'Activate'}</button>}</div>)}</div><p className="muted">{s.provider==='RAZORPAY'?'Payments are processed securely through Razorpay. Subscription status is confirmed by signed checkout verification and server-side webhooks.':'Plan requests create a pending invoice. Activation is intentionally controlled by an RCAA administrator until a payment provider is connected.'}</p></div>
 <div className="panel" style={{marginTop:14}}><h3>Invoices</h3>{d.invoices.length?<Table><thead><tr><th>Invoice</th><th>Status</th><th>Total</th><th>Issued</th><th>Due</th>{s.provider!=='RAZORPAY'&&user?.role==='ADMIN'&&<th>Action</th>}</tr></thead><tbody>{d.invoices.map((i:any)=><tr key={i.id}><td>{i.invoice_number}</td><td><Badge value={i.status}/></td><td>{money(i.total,i.currency)}</td><td>{dateTime(i.issued_at)}</td><td>{dateTime(i.due_at)}</td>{s.provider!=='RAZORPAY'&&user?.role==='ADMIN'&&<td>{i.status!=='PAID'&&<button className="btn secondary" disabled={busy!==''} onClick={()=>paid(i.id)}>{busy==='paid-'+i.id?'Saving…':'Mark paid'}</button>}</td>}</tr>)}</tbody></Table>:<div className="empty">No invoices yet.</div>}</div></>;
}
