from abc import ABC, abstractmethod
from typing import Any

class PaymentProvider(ABC):
    @abstractmethod
    def fetch_payment(self, payment_id: str) -> dict[str, Any]: ...
    @abstractmethod
    def fetch_refund(self, refund_id: str) -> dict[str, Any]: ...
    @abstractmethod
    def fetch_settlements(self, payment_id: str) -> list[dict[str, Any]]: ...
    @abstractmethod
    def verify_webhook(self, body: bytes, signature: str) -> bool: ...
    @abstractmethod
    def normalize_payment(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def normalize_refund(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def normalize_settlement(self, payload: dict[str, Any]) -> dict[str, Any]: ...
